Repository kids-first/kf-uikit, pull requests merged in 2019-04, with the labels that each got.

#96 ⬆️ Upgrade yarn deps
  yarn.lock
Labels: bug

#89 🚑 Hotfix/molten leading values
  src/styles/typography.css
  stories/Typography/Typography.story.jsx
Labels: bug

#102 ♻️ Make header hoverable
  src/components/Header/Header.jsx
  src/components/Header/__tests__/__snapshots__/Header-tests.jsx.snap
Labels: refactor

#98 ✅ Adds Percy.io Visual Testing to CI
  .circleci/config.yml
  .storybook/config.js
  .storybook/preview-head.html
  docs/process/README.md
  package.json
  src/components/Button/Button.story.jsx
  src/components/Button/__tests__/Button-test.jsx
  src/components/Button/__tests__/__snapshots__/Button-test.jsx.snap
  src/components/Card/Card.story.jsx
  src/components/Header/Header.story.jsx
  src/components/Stats/Stats.story.jsx
  src/utils/propsVariants.js
  stories/Colors/Colors.jsx
  stories/Colors/Colors.story.jsx
  stories/Spacing/Spacing.story.jsx
  stories/Typography/Typography.story.jsx
Labels: devops

#110 🐛 Bug fix for style build
  package.json
  src/components/Header/Header.jsx
Labels: bug

#114 🐛 Bug/113 header styling corrections
  src/components/Header/Header.css
Labels: bug, component, style

#106 ⬆️ Feature/storybook version bump v5
  .babelrc
  .storybook/addons.js
  .storybook/config.js
  .storybook/webpack.config.js
  assets/spacing_grid__4px_cells.png
  package.json
  rollup.config.js
  src/components/Card/Card.css
  src/components/Header/Header.css
  src/components/Icon/Icon.story.jsx
  static/kf_uikit.png
  static/spacing_grid__4px_cells.png
  stories/Colors/Colors.jsx
  stories/Spacing/Spacing.story.jsx
  stories/Spacing/assets/bgs_icon.png
  yarn.lock
Labels: documentation, ready-for-review, style

#120 ♻️ Ignore percy in CircleCI
  .circleci/config.yml
Labels: devops

#95 ✨ 12 column grid system
  .gitignore
  .storybook/config.js
  .storybook/preview-head.html
  package.json
  postcss.config.js
  src/.DS_Store
  src/components/Button/Button.plugin.js
  src/components/Card/Card.plugin.js
  src/components/Grid/Grid.css
  src/components/Grid/Grid.story.jsx
  src/components/Grid/GridContainer.jsx
  src/components/Grid/__tests__/GridContainer-test.jsx
  src/components/Grid/__tests__/__snapshots__/GridContainer-test.jsx.snap
  src/components/Icon/Icon.plugin.js
  src/components/index.jsx
  src/index.jsx
  src/tailwind.src.css
  src/utils/propsVariants.js
Labels: component, feature, ready-for-review, style

#122 ⬆️ Upgrade babel to 7
  package.json
  yarn.lock
Labels: refactor

#123 🔥 Remove .DS_Store
  src/.DS_Store
Labels: bug

#121 🔧 Export bablified js
  index.js
Labels: bug, refactor

#103 ✨ Add button with icon
  src/components/Button/Button.css
  src/components/Button/Button.jsx
  src/components/Button/Button.story.jsx
  src/components/Button/__tests__/Button-test.jsx
  src/components/Button/__tests__/__snapshots__/Button-test.jsx.snap
Labels: feature, style

#127 🔧 use STORYBOOK_PERCY_ENV for yarn snapshot
  .storybook/config.js
  package.json
  src/components/Button/Button.story.jsx
  src/components/Grid/Grid.story.jsx
  src/components/Logo/Logo.story.jsx
  src/components/Stats/Stats.story.jsx
  yarn.lock
Labels: devops

#105 ✨ Add SecondaryNav component
  .storybook/config.js
  src/components/SecondaryNav/SecondaryNav.css
  src/components/SecondaryNav/SecondaryNav.jsx
  src/components/SecondaryNav/SecondaryNav.story.jsx
  src/components/SecondaryNav/SecondaryNavLink.jsx
  src/components/SecondaryNav/__tests__/SeconadryNav-tests.jsx
  src/components/SecondaryNav/__tests__/__snapshots__/SeconadryNav-tests.jsx.snap
  src/index.jsx
Labels: component, feature

#109 ✨ Add avatar component
  .storybook/config.js
  package.json
  src/components/Avatar/Avatar.css
  src/components/Avatar/Avatar.jsx
  src/components/Avatar/Avatar.story.jsx
  src/components/Avatar/__tests__/Avatar-test.jsx
  src/components/Avatar/__tests__/__snapshots__/Avatar-test.jsx.snap
  src/index.jsx
  yarn.lock
Labels: component, feature

#112 ✨ Add dropdown menu component
  .storybook/config.js
  src/components/Dropdown/Dropdown.css
  src/components/Dropdown/Dropdown.jsx
  src/components/Dropdown/Dropdown.story.jsx
  src/components/Dropdown/__tests__/Dropdown-test.jsx
  src/components/Dropdown/__tests__/__snapshots__/Dropdown-test.jsx.snap
  src/index.jsx
Labels: component, feature, ready-for-review

#129 🔥 Remove lodash from Avatar
  src/components/Avatar/Avatar.jsx
Labels: bug

#130 👷 Ensure bundle builds without error in CI
  .circleci/config.yml
Labels: devops

#131 👷 Bundle size status check
  .circleci/config.yml
  package.json
Labels: devops
